### ISSUE TITLE
Value error if I try to run APLAutoHotKey.Run 2

### ISSUE THREAD

**Issue by dyavc** [Dyalog/APLAutoHotKey#29]
because of the length error #27 , I tried to run APLAutoHotKey.Run 2

I then get a value error because I don't have CiderConfig.HOME

I do have cider and tatin:

APLAutoHotKey version 1.0.0

]cider.version
0.30.0+410
      ]tatin.version
 Tatin  0.98.0+1611  2023-07-05 

Dyalog  18.2.47709 64-bit Unicode, BuildID f7e2626f            
 OS      Windows 10 or Windows Server 2016 (10.0.19045) 64-bit  
 Link    3.0.19                                                 
 SALT    2.9                                                    
 UCMD    2.51                                                   
 .NET    .NET Framework 4.8.4645.0                              
 WS      18.2

**Comment by rikedyp** [comment]
You have to open the project using Cider in order to do development with it.

1. Clone this repository
2. Do `]CIDER.OpenProject /path/to/repo/folder`
